name: Main
on: push
jobs:
  ci:
    name: CI
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 2.5, 2.6, 2.7, jruby ]
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: bundle install --jobs 4 --retry 3
    - run: bundle exec rubocop
    - run: bundle exec rspec
