name: Main
on: push
jobs:
  ci:
    name: CI
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 2.5, 2.6, 2.7, jruby ]
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle list
    - run: bundle info rubocop
    - run: tree vendor/bundle/*/2.*.0/gems/rubocop-0.88.0
    - run: bundle exec rubocop -h
      env:
        RUBYOPT: "-d"
    - run: bundle exec rubocop
    - run: bundle exec rspec
